SRC_DIR = . ./librtmp
INC_DIR = ./ ../ \
		  ./librtmp \
		  ../../deps/include \
		  ../../mgw-core \
		  ../../mgw-core/include

OBJ_DIR = .

LIB_DIR = . \
		  ../../deps/lib/x86 \
		  ../../mgw-core/buffer \
		  ../../mgw-core/source \
		  ../../mgw-core/util \


TARGET = libmgw-outputs.so
TARGET_TYPE = "shared"
LIBS = 
CFLAGS = -fvisibility=hidden

include $(PROJECT_ROOT_PATH)/compile_rules.mk