SRC_DIR = ./

INC_DIR = ../ \
		  ../../deps/include \
		  ../include \
		  ../../plugins

LIB_DIR = . \
		  ../../deps/lib

TARGET = libmgw-core.so
TARGET_TYPE = "shared"
LIBS =

include $(PROJECT_ROOT_PATH)/compile_rules.mk