SRC_DIR = .

INC_DIR = ./ ../ \
		  ../../deps/include \
		  ../../mgw-core \
		  ../../mgw-core/include

LIB_DIR = . \
		  ../../deps/lib

TARGET = libmgw-sources.so
TARGET_TYPE = "shared"
LIBS =

include $(PROJECT_ROOT_PATH)/compile_rules.mk