
all:
	$(MAKE)	-C	util
	$(MAKE)	-C	buffer
	$(MAKE)	-C	core-api

.PHONY:clean
clean:
	$(MAKE)	-C	util clean
	$(MAKE)	-C	buffer clean
	$(MAKE)	-C	core-api clean

.PHONY: install
install:
	$(MAKE)	-C	util install
	$(MAKE)	-C	buffer install
	$(MAKE)	-C	core-api install