
all:
	$(MAKE)	-C	util
	$(MAKE)	-C	buffer
	$(MAKE)	-C	source

.PHONY:clean
clean:
	$(MAKE)	-C	util clean
	$(MAKE)	-C	buffer clean
	$(MAKE)	-C	source clean

.PHONY: install
install:
	$(MAKE)	-C	util install
	$(MAKE)	-C	buffer install
	$(MAKE)	-C	source install